# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty            #'/:title/'
relative_permalinks:  false

plugins:              [jekyll-paginate]
exclude:              [
                        'node_modules',
                        'gulpfile.babel.js',
                        'package.json',
                        '_sass',
                        '_js',
                        '_draft',
                        '.sass-cache'
                      ]

# Setup
title:                "The Economist"
tagline:              "为你, 千千万万遍"
description:          '<b>Published since September 1843</b> <i>to take part in "a severe contest between intelligence, which presses forward, and an unworthy, timid ignorance obstructing our progress.</i>"'
url:                  https://xmuplus.github.io
baseurl:              ''
paginate:             5
paginate_path:        'page-:num'
excerpt_separator:    <!--more-->

# About/contact
author:
  name:               
  url:                https://xmuplus.github.io
  email:              

# Issues
newest:               2019.01.12
issue :
       num_capital:   JANUARY 12TH-18TH 2019
       num_small:     January 12th-18th 2019
       size:          16.5
       desc:          "Holiday double issue"
  

random:               acfnun76

# Epub/url
epub:
       file:  
       pass:  
       size:  

# Mobi/url
mobi:
       file:  
       pass:  
       size: 




# <hr/> color
hr_color:
         donate: e1e1e1
         home: d4d4d4

# Comment
comment:
    #disqus: 

# Google Analytics
google_analytics: UA-82090560-3


# Sass
# sass:
#   sass_dir:           _sass
#   style:              compressed

# destination: public/output

deploy:
  - type: rsync
    user: root
    host: 
    dir:  /data/wwwroot/
